# Generated by Django 5.1.4 on 2024-12-19 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('adventure', 'adventure'), ('culture', 'culture'), ('budget', 'budget'), ('luxury', 'luxury'), ('backpacking', 'backpacking'), ('sightseeing', 'sightseeing'), ('nature', 'nature'), ('food', 'food'), ('beach', 'beach'), ('city', 'city'), ('mountain', 'mountain'), ('historical', 'historical'), ('solo', 'solo'), ('family', 'family'), ('romantic', 'romantic'), ('road_trip', 'road_trip'), ('eco_tourism', 'eco_tourism'), ('wildlife', 'wildlife'), ('festivals', 'festivals'), ('adventure_sports', 'adventure_sports'), ('urban_exploration', 'urban_exploration')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='blog.tag')),
            ],
        ),
    ]
